### ISSUE TITLE
PR 71 marks builds with catched errors as failed

### ISSUE THREAD

**Issue by arthur-c** [jenkinsci/github-autostatus-plugin#72] opened 2019-10-29 17:13 UTC
Hi,

The PR #71  which solved #47 marks builds which contains a catched error as failed in GitHub. The Build is OK in Jenkins.

It blocks all the Github repos that have build conditions for merging.

Catching error is a native groovy function that works in Jenkins, github-autostatus-plugin should follow the Jenkins behaviour.

**Comment by jeffpearce** [comment] 2019-10-29 17:27
Does it actually fail the build, or just the stage?

I'm ambivalent since I don't rely on caught errors, but the point @robkorv made in #47 about it matching what's shown in pipeline view seemed correct.

**Comment by arthur-c** [comment] 2019-10-29 18:36
@jeffpearce it's fails the stage and the build on github. It fails only the step on jenkins.

Yes @dblock is a bit "more right" than me because he is using native jenkins DSL but the groovy try-catch is documented by Jenkins itself: https://jenkins.io/doc/book/pipeline/syntax/#flow-control

We downgraded the plugin version and it works fine. 

I understand that's a bit tricky, but maybe we can mark the stage as failed if a step failed without being catched ?

**Comment by awiddersheim** [comment] 2019-11-06 15:50
We just upgraded and are also battling this as something that is annoying. Simple to recreate with:

```
            try {
                sh 'exit 1'
            } catch (Exception ignored) {
                // Do nothing here we are okay with errors
            }
```

This is a fairly valid use case IMO. In GitHub we mark that particular stage as not being required so we can continue on but it still sends a false signal as something went wrong when it didn't.

**Comment by robkorv** [comment] 2019-11-07 09:43
Might this have something todo that the default of `catchError` is `buildResult: 'FAILURE', stageResult: 'SUCCESS' and the `catch` uses that setting while it previous did not?

You might be able to fix this by setting the result that you want in the `catch` for now.
```groovy
node {
    try {
        sh 'might fail'
    } catch (err) {
        echo "Caught: ${err}"
        currentBuild.result = 'SUCCESS'
    }
    step([$class: 'Mailer', recipients: 'admin@somewhere'])
}
```

I do think that when you use `catch` that no errors gets set is the expected behavior, while my request in https://github.com/jenkinsci/github-autostatus-plugin/issues/47 is also expected behavior.

**Comment by awiddersheim** [comment] 2019-11-07 23:39
I feel like what is happening in https://github.com/jenkinsci/github-autostatus-plugin/pull/71 is that it is going one layer to deep and examining each _step_ for a failure rather than just evaluation each _stage_.

**Comment by jeffpearce** [comment] 2019-11-08 18:57
There was a request to make the plugin match the pipeline UI, which marks the stage as a failure if any step failed, even if the exception is caught and handled. In retrospect, I don't think that makes sense for this plugin, so I'll revert the behavior to just report the official stage result.

**Comment by awiddersheim** [comment] 2019-11-08 19:09
Well, the original ask in #47 was::

```
catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE')
```

This is setting the entire build as a success but the stage itself as a failure. This also means the _step_ failed as well but for whatever reason the way errors are checked for now is not seeing the  `stageResult` condition. This is similar to how the `try/catch` is happening where the _step_ fails but not the stage.

I guess `catchError()` is storing stages results in a different place than where this plugin might be checking?

**Comment by jeffpearce** [comment] 2019-12-30 16:59
I should have a fix for this in the next release that handles the original ask, and doesn't send spam errors when an error is caught

**Comment by snowblink** [comment] 2020-01-09 10:56
Wondering if you had an ETA for this fix?

**Comment by jeffpearce** [comment] 2020-01-12 15:45
Please try release 3.6.1 and let me know if you are still having issues

**Closed by jeffpearce** 2020-01-12 15:45 UTC
